### ISSUE TITLE
obstructed? method not checking all squares

### ISSUE THREAD

**Issue by addstar34** [teamendgame/endgame-chess#52]
The obstructed? method is only checking 1 square from the destination and not all squares from the piece to its destination as we thought it was.

Eg: A queen in row 5 col 5 wants to go to row 2 col 2. The current obstructed? method will only check row 3 col 3 and return true/false based on if there is a piece there. In this scenario it should also check row 4 col 4.

**Comment by jonathanpike** [comment]
Fixed with #53
