### ISSUE TITLE
When capturing, piece jumps to an adjacent square

### ISSUE THREAD

**Issue by jonathanpike** [teamendgame/endgame-chess#64]
With @ronny2205 and @gagaception's fancy drag and drop, we have a small visual bug. I'll visually demonstrate: 

First, we have a piece that we can capture: 
![screen shot 2015-12-18 at 5 25 30 am](https://cloud.githubusercontent.com/assets/8129357/11894908/622c9c3c-a548-11e5-851c-3f36887bb19f.png)

We move to capture it: 
![screen shot 2015-12-18 at 5 26 15 am](https://cloud.githubusercontent.com/assets/8129357/11894914/68726874-a548-11e5-8dab-32daf8f73794.png)

It then snaps to an adjacent square: 
![screen shot 2015-12-18 at 5 26 24 am](https://cloud.githubusercontent.com/assets/8129357/11894927/71d15998-a548-11e5-9d5a-021c818f063c.png)

Looking at Chrome's Dev Tools will give us an idea of what's happening: 
![screen shot 2015-12-18 at 5 28 03 am](https://cloud.githubusercontent.com/assets/8129357/11894932/81babebc-a548-11e5-8a9b-a1001dd15dcc.png)

As you can see, both pieces exist in the same table cell, and since the table cell is constrained to certain proportions, the one piece gets shifted away.   

A simple solution would be to take the captured piece off the board immediately with some javascript.  Maybe setting it to `display: none;` would work, although I'm not sure about that.

**Comment by takehiromouri** [comment]
@jonathanpike Thanks for a well explained issue.

As @jonathanpike  mentioned, I think a good solution to this would be to create a class with `display:none` and change the class of the piece to it, or just do `hide()`.

The page is refreshed nonetheless so we don't have to do anything on the backend do we?

**Comment by jonathanpike** [comment]
No, we don't have to do anything on the back end.  I'm playing around with jQuery to see if I can just hide the piece that is being captured.  

I've tested `display: none`, and unfortunately it doesn't work.  The captured piece is the parent of the capturing piece, so it hides them both.

**Comment by jonathanpike** [comment]
Solved in #63
