### ISSUE TITLE
User should only be able to see games they are involved in

### ISSUE THREAD

**Issue by jonathanpike** [teamendgame/endgame-chess#68]
This is less of an issue and more of a discussion.  I'd love to have your opinions.  

As it stands, on the "Find Game" page, we only show games that you're currently involved in under the heading "My Games".  However, if you are on a game show page and enter other game IDs in the URL, you can access any game that you would like to see, even games that you're not playing.  I personally think this is not the behaviour we want, and so we should add a `before_action` in the games controller that checks if `current_user.id` matches with either `black_player_id` or `white_player_id`, and if not, displays a flash notice telling the user that they are not authorized to see this game. 

What do you guys think?

**Comment by jonathanpike** [comment]
Additionally, if a game is waiting for a player, we should show this on the game show page.  This is currently how a game looks if the second player has not joined: 

![screenshot 2015-12-23 10 58 56](https://cloud.githubusercontent.com/assets/8129357/11979831/7222535a-a964-11e5-96c4-3972e71c7d42.png)

No indication of what's going on!  While a user wouldn't normally go to this page, we have to either prevent them from doing so OR show that the game is currently waiting for a second player (and perhaps have a join button on the page).

**Comment by ronny2205** [comment]
I totally agree with both ideas. I think we shouid do both.

**Comment by jonathanpike** [comment]
Fixed in #77
