### ISSUE TITLE
Add indexes to database

### ISSUE THREAD

**Issue by jonathanpike** [teamendgame/endgame-chess#9]
Indexing our associations will make database lookups a lot faster.  I found this really great article that explains the performance benefits: https://tomafro.net/2009/08/using-indexes-in-rails-index-your-associations

**Comment by takehiromouri** [comment]
@jonathanpike Nice read, you're really good at pulling up great articles/resources. I'll create a branch and add these indices in.

**Comment by jonathanpike** [comment]
Closed with PR #11
